UPDATE [LQCE].[dbo].[TIPO_FACTURA]
   SET [NOMBRE_REPORTE_FACTURA_INDIVIDUAL] = 'Factura_LQCE_IVA.rdlc'
 WHERE ID = 1 
GO
UPDATE [LQCE].[dbo].[TIPO_FACTURA]
   SET [NOMBRE_REPORTE_FACTURA_INDIVIDUAL] = 'Factura_LQCE_Exento.rdlc'
 WHERE ID = 2 
GO
UPDATE [LQCE].[dbo].[TIPO_FACTURA]
   SET [NOMBRE_REPORTE_FACTURA_INDIVIDUAL] = 'Factura_Monari_IVA.rdlc'
 WHERE ID = 3 
GO
UPDATE [LQCE].[dbo].[TIPO_FACTURA]
   SET [NOMBRE_REPORTE_FACTURA_INDIVIDUAL] = 'Factura_Monari_Exento.rdlc'
 WHERE ID = 4 
GO


